import { formatLargeNumber } from './math-utils.js';
import { detectiveCases } from './detective-cases.js';

const $=id=>document.getElementById(id);let currentIndex=0,hasRun=false,chart=null;
const labels={log:'O(log n)',linear:'O(n)',nlogn:'O(n log n)',quadratic:'O(n²)',cubic:'O(n³)',exponential:'O(2ⁿ)'};
function current(){return detectiveCases[currentIndex];}
function renderRows(count){$('evidenceBody').innerHTML=current().values.slice(0,count).map(value=>`<tr><td>${new Intl.NumberFormat('en-US').format(value.n)}</td><td class="text-end">${formatLargeNumber(value.operations)}</td></tr>`).join('');}
function loadCase(index){currentIndex=index;$('caseSelect').value=String(index);$('caseTitle').textContent=current().title;renderRows(3);document.querySelectorAll('[name=model]').forEach(input=>input.checked=false);$('runButton').disabled=true;$('checkButton').disabled=true;$('predictionHint').textContent='Selecciona un modelo para habilitar el experimento.';$('graphPanel').classList.add('d-none');$('observe').classList.add('d-none');$('explain').classList.add('d-none');$('checkFeedback').innerHTML='';$('caseExplanation').classList.add('d-none');$('caseExplanation').innerHTML='';$('explanation').value='';hasRun=false;if(chart){chart.dispose();chart=null;}}
function run(){renderRows(current().values.length);$('graphPanel').classList.remove('d-none');$('observe').classList.remove('d-none');$('explain').classList.remove('d-none');$('checkButton').disabled=false;const first=current().values[0].n,second=current().values[1].n,multiplier=second/first;$('ratioPrompt').textContent=`What happens to the number of operations when n is multiplied by ${Number.isInteger(multiplier)?multiplier:multiplier.toFixed(2)}?`;if(!chart)chart=echarts.init($('detectiveChart'));chart.setOption({animation:false,tooltip:{trigger:'axis'},grid:{left:78,right:25,top:25,bottom:65},xAxis:{type:'log',name:'n',nameLocation:'middle',nameGap:38},yAxis:{type:'log',name:'operations'},dataZoom:[{type:'inside'},{type:'slider',bottom:10}],series:[{name:'Observed operations',type:'line',symbolSize:9,data:current().values.map(value=>[value.n,value.operations])}]},true);chart.resize();hasRun=true;$('experimentHint').textContent='Nueva evidencia revelada. Examina el patrón antes de comprobar tu predicción.';localStorage.setItem('algorithmPlayground.lastModule','detective');}
function check(){if(!hasRun)return;const prediction=document.querySelector('[name=model]:checked')?.value,correct=prediction===current().complexity;$('checkFeedback').innerHTML=`<div class="alert alert-${correct?'success':'warning'} mb-0"><strong>${correct?'Correct!':'Not quite.'}</strong> ${correct?`The generating model was ${labels[current().complexity]}.`:'Use the new observation and compare multiplicative changes before trying again.'}</div>`;if(correct){$('caseExplanation').classList.remove('d-none');$('caseExplanation').innerHTML=`<div class="alert alert-info mb-0"><strong>Model explanation:</strong> ${current().explanation}<br><small>This identifies the data generator, not a mathematical proof of an algorithm's asymptotic complexity.</small></div>`;}}
function populateSelect(){$('caseSelect').innerHTML=detectiveCases.map((item,index)=>`<option value="${index}">${item.title}</option>`).join('');}
populateSelect();document.querySelectorAll('[name=model]').forEach(input=>input.addEventListener('change',()=>{$('runButton').disabled=false;$('predictionHint').textContent='Predicción registrada. Ya puedes revelar evidencia adicional.';if(hasRun)$('checkButton').disabled=false;}));$('runButton').addEventListener('click',run);$('checkButton').addEventListener('click',check);$('resetButton').addEventListener('click',()=>loadCase(currentIndex));$('caseSelect').addEventListener('change',()=>loadCase(Number($('caseSelect').value)));$('newCaseButton').addEventListener('click',()=>{let next;do{next=Math.floor(Math.random()*detectiveCases.length);}while(next===currentIndex);loadCase(next);});window.addEventListener('resize',()=>chart?.resize());loadCase(0);
