import './algorithms/index.js';
import {executeAlgorithm} from './core/algorithm-engine.js';
import {createCheckpointSession} from './core/decision-checkpoints.js';
import {renderCheckpoint,renderCheckpointFeedback} from './core/checkpoint-renderer.js';
import {crossingEdges,minimumCrossingEdges,cycleMaximumEdges} from './core/mst-analysis.js';
import {mstInstances,cloneMstGraph} from './data/mst-instances.js';
const $=id=>document.getElementById(id);let graph,primRun,primIndex=0,kruskalRun,kruskalIndex=0;
mstInstances.forEach(item=>$('mstInstance').add(new Option(item.name,item.id)));document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('.mst-view').forEach(x=>x.classList.add('d-none'));$(`${button.dataset.view}View`).classList.remove('d-none');}));
function loadGraph(){graph=cloneMstGraph($('mstInstance').value);$('uniquenessBadge').textContent=graph.allowsMultipleSolutions?'Tied weights · multiple MSTs':'Repeated weights · known unique MST';renderCutControls();renderCycleControls();$('safeFeedback').innerHTML='';$('cycleFeedback').innerHTML='';primRun=kruskalRun=null;compareAlgorithms();}
function renderGraph(host,data,state={}){const vertices=Object.fromEntries(data.vertices.map(v=>[v.id,v])),selected=new Set((state.selectedEdges??[]).map(e=>typeof e==='string'?e:e.id)),rejected=new Set((state.rejectedEdges??[]).map(e=>typeof e==='string'?e:e.id)),crossing=new Set(state.crossingEdges??[]),inside=new Set(state.inside??[]);host.innerHTML=`<svg viewBox="0 0 100 100" aria-hidden="true">${data.edges.map(e=>{const a=vertices[e.from],b=vertices[e.to],mx=(a.x+b.x)/2,my=(a.y+b.y)/2,kind=selected.has(e.id)?'selected':rejected.has(e.id)?'rejected':crossing.has(e.id)?'crossing':'';return `<g class="graph-edge ${kind} ${state.activeEdge===e.id?'active':''}"><line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}"/><text x="${mx}" y="${my-2}">${e.weight}</text><text x="${mx}" y="${my+4}">${e.id}</text></g>`}).join('')}</svg>${data.vertices.map(v=>`<button class="graph-vertex ${inside.has(v.id)?'fixed':''}" style="left:${v.x}%;top:${v.y}%" aria-label="Vertex ${v.id}">${v.id}</button>`).join('')}`;}
function renderCutControls(){$('cutVertexChoices').innerHTML=graph.vertices.map(v=>`<label class="checkpoint-option"><input type="checkbox" value="${v.id}"> ${v.id}</label>`).join('');$('cutVertexChoices').querySelector('input').checked=true;updateCut();}
function updateCut(){const selected=[...$('cutVertexChoices').querySelectorAll(':checked')].map(x=>x.value),crossing=crossingEdges(graph,selected),minimum=minimumCrossingEdges(graph,selected);renderGraph($('cutGraph'),graph,{inside:selected,crossingEdges:crossing.map(e=>e.id)});$('cutEdges').innerHTML=`<strong>δ(S):</strong> ${crossing.map(e=>`${e.id} (${e.weight})`).join(', ')||'no crossing edges'}`;$('safeEdge').innerHTML='<option value="">Choose edge</option>'+crossing.map(e=>`<option value="${e.id}">${e.id} · weight ${e.weight}</option>`).join('');$('safeEdge').dataset.valid=minimum.map(e=>e.id).join(',');}
function renderCycleControls(){const cycle=['AB','BC','AC'].filter(id=>graph.edges.some(e=>e.id===id));$('cycleChoices').innerHTML=cycle.length?cycle.map(id=>`<label class="checkpoint-option"><input type="radio" name="cycleEdge" value="${id}"> ${id} · weight ${graph.edges.find(e=>e.id===id).weight}</label>`).join(''):'<p>This instance has no designated A–B–C triangle; choose the Unique MST instance for this activity.</p>';$('cycleChoices').dataset.cycle=cycle.join(',');}
function checkSafe(){const selected=[...$('cutVertexChoices').querySelectorAll(':checked')].map(x=>x.value);if(!selected.length||selected.length===graph.vertices.length){$('safeFeedback').innerHTML='<div class="alert alert-warning">Choose a nonempty proper subset S.</div>';return;}const valid=$('safeEdge').dataset.valid.split(',').includes($('safeEdge').value),ties=$('safeEdge').dataset.valid.includes(',');$('safeFeedback').innerHTML=`<div class="alert alert-${valid?'success':'warning'}">${valid?`Safe choice: it has minimum weight across this cut.${ties?' A tie means some MST contains this edge, not necessarily every MST.':''}`:'Choose a minimum-weight edge crossing δ(S).'}</div>`;}
function checkCycle(){const ids=$('cycleChoices').dataset.cycle.split(',').filter(Boolean),maximum=cycleMaximumEdges(graph,ids).map(e=>e.id),answer=document.querySelector('[name=cycleEdge]:checked')?.value,correct=maximum.includes(answer);$('cycleFeedback').innerHTML=`<div class="alert alert-${correct?'success':'warning'}">${correct?'A maximum-weight edge on this cycle may be excluded. With ties, exclusion need not be unique.':'Inspect the maximum edge weight on the displayed cycle.'}</div>`;}
function startPrim(){primRun=executeAlgorithm('prim',graph);primIndex=0;showPrim();}
function showPrim(){const step=primRun.trace[primIndex];renderGraph($('primGraph'),graph,{inside:step.structures.inside,selectedEdges:step.structures.treeEdges,activeEdge:step.visualization.activeEdge});$('primStatus').innerHTML=`<strong>Step ${primIndex+1}/${primRun.trace.length}</strong> · T vertices = {${step.structures.inside.join(', ')}} · ${step.message.en}`;$('primTable').innerHTML=`<table class="table table-sm"><thead><tr><th>v</th><th>key</th><th>pred</th></tr></thead><tbody>${graph.vertices.map(v=>`<tr><th>${v.id}</th><td>${fmt(step.structures.keys[v.id])}</td><td>${step.structures.predecessors[v.id]??'—'}</td></tr>`).join('')}</tbody></table>`;$('primQueue').innerHTML=step.structures.queue.map((x,i)=>`<div class="queue-item ${i===0?'minimum':''}"><span>${x.vertex}</span><strong>${fmt(x.key)}</strong></div>`).join('');$('primSummary').innerHTML=`<strong>Tree edges:</strong> ${step.structures.treeEdges.map(e=>e.id).join(', ')||'none'}<br><strong>Total weight:</strong> ${step.structures.totalWeight}`;renderPrimCheckpoint(step);}
function renderPrimCheckpoint(step){const host=$('primCheckpoint');host.innerHTML='';let cp;if(step.checkpointId?.startsWith('prim-extract'))cp={id:step.checkpointId,responseType:'select-visual-object',prompt:{en:'Which minimum-key vertex may Prim extract next?'},options:step.structures.queue.map(x=>({id:x.vertex,label:{en:`${x.vertex} · key ${fmt(x.key)}`}})),validAnswers:step.variables.tiedVertices,hints:[{en:'Choose a minimum key; all tied minima are accepted.'}],explanation:{en:'The predecessor edge of the extracted vertex enters T. The root has no predecessor edge.'}};else if(step.type==='considerCandidate')cp={id:step.checkpointId,responseType:'multiple-choice',prompt:{en:`What happens to ${step.variables.v} through edge ${step.variables.u}—${step.variables.v}?`},options:[{id:'change',label:{en:'Update the key'}},{id:`key-${step.variables.weight}`,label:{en:`New key is ${step.variables.weight}`}},{id:`pred-${step.variables.u}`,label:{en:`New predecessor is ${step.variables.u}`}},{id:'keep',label:{en:'Keep the old key'}}],validAnswers:step.variables.changes?['change',`key-${step.variables.weight}`,`pred-${step.variables.u}`]:['keep'],stateProjection:{values:{edgeWeight:step.variables.weight,oldKey:fmt(step.variables.oldKey)}},hints:[{en:'Prim compares w(u,v), not a source-path distance.'}],explanation:{en:step.variables.changes?'The lighter connecting edge updates both key and predecessor.':'The current connecting edge remains lighter.'}};else if(step.checkpointId?.startsWith('prim-changes'))cp={id:step.checkpointId,responseType:'multiple-choice',prompt:{en:'Which outside vertices received smaller keys?'},options:step.variables.outside.map(v=>({id:v,label:{en:v}})),validAnswers:step.variables.changedVertices,hints:[{en:'Use the edges crossing (V(T), V − V(T)).'}],explanation:{en:`The certifying cut is ({${step.structures.inside.join(', ')}}, {${step.variables.outside.join(', ')}}).`}};if(cp)mount(host,cp);}
function startKruskal(){kruskalRun=executeAlgorithm('kruskal',graph);kruskalIndex=0;showKruskal();}
function showKruskal(){const step=kruskalRun.trace[kruskalIndex];renderGraph($('kruskalGraph'),graph,{selectedEdges:step.structures.accepted,rejectedEdges:step.structures.rejected,activeEdge:step.visualization.activeEdge});$('kruskalStatus').innerHTML=`<strong>Step ${kruskalIndex+1}/${kruskalRun.trace.length}</strong> · ${step.message.en}`;$('edgeOrder').innerHTML=step.structures.ordered.map(e=>`<span class="candidate ${step.structures.accepted.some(x=>x.id===e.id)?'SELECTED':step.structures.rejected.some(x=>x.id===e.id)?'REJECTED':''}">${e.id} (${e.weight})</span>`).join('');const groups={};for(const [vertex,root] of Object.entries(step.structures.components))(groups[root]??=[]).push(vertex);$('components').innerHTML=Object.entries(groups).map(([root,vertices])=>`<div class="component-box"><strong>${root}</strong>: {${vertices.join(', ')}}</div>`).join('');$('kruskalSummary').innerHTML=`<strong>Accepted:</strong> ${step.structures.accepted.length}/${graph.vertices.length-1}<br><strong>Total weight:</strong> ${step.structures.totalWeight}`;renderKruskalCheckpoint(step);}
function renderKruskalCheckpoint(step){const host=$('kruskalCheckpoint');host.innerHTML='';if(step.type!=='considerCandidate')return;const cp={id:step.checkpointId,responseType:'accept-reject',prompt:{en:`Accept or reject ${step.variables.edgeId}?`},options:[{id:'accept',label:{en:'Accept and union'}},{id:'reject',label:{en:'Reject: cycle'}}],validAnswers:[step.variables.accept?'accept':'reject'],stateProjection:{values:{[`find(${step.variables.u})`]:step.variables.componentU,[`find(${step.variables.v})`]:step.variables.componentV}},hints:[{en:'Accept exactly when the endpoint components differ.'}],explanation:{en:step.variables.accept?'The endpoints are in different components, so union is safe.':`The existing path ${step.variables.cyclePath.join(' → ')} plus this edge forms a cycle.`}};mount(host,cp);}
function mount(host,cp){const session=createCheckpointSession(cp);renderCheckpoint(host,cp,{onSubmit:(response,node)=>renderCheckpointFeedback(node,session.submit(response)),onHint:node=>renderCheckpointFeedback(node,session.hint()),onReveal:node=>renderCheckpointFeedback(node,session.reveal())});}
function move(kind,delta){const run=kind==='prim'?primRun:kruskalRun;if(!run)return;if(kind==='prim'){primIndex=Math.max(0,Math.min(run.trace.length-1,primIndex+delta));showPrim();}else{kruskalIndex=Math.max(0,Math.min(run.trace.length-1,kruskalIndex+delta));showKruskal();}}
function compareAlgorithms(){const prim=executeAlgorithm('prim',graph),kruskal=executeAlgorithm('kruskal',graph),same=[...prim.result.edges].sort().join(',')===[...kruskal.result.edges].sort().join(',');$('algorithmComparison').innerHTML=`<p><strong>Prim:</strong> ${prim.result.edges.join(', ')} · weight ${prim.result.totalWeight}<br><strong>Kruskal:</strong> ${kruskal.result.edges.join(', ')} · weight ${kruskal.result.totalWeight}</p><div class="alert alert-${same?'success':'info'}">${same?'These deterministic runs selected the same MST.':'They selected different edge sets with the same optimal total weight.'}</div>`;}
function fmt(v){return v===Infinity?'∞':v;}
$('mstInstance').addEventListener('change',loadGraph);$('cutVertexChoices').addEventListener('change',updateCut);$('checkSafeEdge').addEventListener('click',checkSafe);$('checkCycle').addEventListener('click',checkCycle);$('startPrim').addEventListener('click',startPrim);$('primPrev').addEventListener('click',()=>move('prim',-1));$('primNext').addEventListener('click',()=>move('prim',1));$('startKruskal').addEventListener('click',startKruskal);$('kruskalPrev').addEventListener('click',()=>move('kruskal',-1));$('kruskalNext').addEventListener('click',()=>move('kruskal',1));loadGraph();
