import { factorial } from './math-utils.js';

const $=id=>document.getElementById(id);
const families=[
  {id:'constant',label:'1',value:()=>1},
  {id:'log',label:'log₂ n',value:n=>Math.log2(n)},
  {id:'sqrt',label:'√n',value:n=>Math.sqrt(n)},
  {id:'linear',label:'n',value:n=>n},
  {id:'nlogn',label:'n log₂ n',value:n=>n*Math.log2(n)},
  {id:'quadratic',label:'n²',value:n=>n**2},
  {id:'cubic',label:'n³',value:n=>n**3},
  {id:'exponential',label:'2ⁿ',value:n=>2**n},
  {id:'factorial',label:'n!',value:n=>factorial(n)}
];
const correct=families.map(item=>item.id);let order=[],draggedId=null,chart=null;

function shuffle(items){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;}
function render(){const list=$('raceList');list.innerHTML='';order.forEach((id,index)=>{const item=families.find(f=>f.id===id),li=document.createElement('li');li.className='race-item';li.draggable=true;li.dataset.id=id;li.innerHTML=`<span class="race-position" aria-hidden="true">${index+1}</span><strong>${item.label}</strong><span class="ms-auto d-flex gap-1"><button class="btn btn-sm btn-light move-up" type="button" aria-label="Mover ${item.label} una posición hacia crecimiento más lento" ${index===0?'disabled':''}>←</button><button class="btn btn-sm btn-light move-down" type="button" aria-label="Mover ${item.label} una posición hacia crecimiento más rápido" ${index===order.length-1?'disabled':''}>→</button></span>`;li.addEventListener('dragstart',()=>{draggedId=id;li.classList.add('dragging');});li.addEventListener('dragend',()=>{draggedId=null;li.classList.remove('dragging');});li.addEventListener('dragover',event=>event.preventDefault());li.addEventListener('drop',event=>{event.preventDefault();moveBefore(draggedId,id);});li.querySelector('.move-up').addEventListener('click',()=>move(index,-1));li.querySelector('.move-down').addEventListener('click',()=>move(index,1));list.append(li);});}
function move(index,direction){const next=index+direction;if(next<0||next>=order.length)return;[order[index],order[next]]=[order[next],order[index]];render();}
function moveBefore(source,target){if(!source||source===target)return;order.splice(order.indexOf(source),1);order.splice(order.indexOf(target),0,source);render();}
function check(){const wrong=order.reduce((count,id,index)=>count+(id!==correct[index]),0);$('feedbackSection').classList.remove('d-none');$('feedback').innerHTML=wrong===0?'<div class="alert alert-success mb-0"><strong>Correct!</strong> Your order matches the asymptotic growth hierarchy.</div>':`<div class="alert alert-warning mb-0"><strong>Not quite.</strong><br>${wrong} ${wrong===1?'function is':'functions are'} in the wrong position. Adjust the cards and try again.</div>`;$('feedbackSection').scrollIntoView({behavior:'smooth',block:'nearest'});}
function showGraph(){const panel=$('graphPanel'),visible=!panel.classList.contains('d-none');panel.classList.toggle('d-none');$('graphButton').textContent=visible?'Show graph':'Hide graph';if(visible)return;if(!chart)chart=echarts.init($('raceChart'));const ns=Array.from({length:15},(_,i)=>i+1);chart.setOption({animation:false,tooltip:{trigger:'axis'},legend:{type:'scroll',top:0},grid:{left:72,right:25,top:55,bottom:60},xAxis:{type:'value',name:'n',nameLocation:'middle',nameGap:32,min:1,max:15},yAxis:{type:'log',name:'valor'},dataZoom:[{type:'inside'},{type:'slider',bottom:8}],series:families.map(item=>({name:item.label,type:'line',showSymbol:false,data:ns.map(n=>{const value=item.value(n);return[n,Number.isFinite(value)&&value>0?value:null];})}))},true);chart.resize();}
function showAnswer(){const panel=$('answerPanel'),visible=!panel.classList.contains('d-none');panel.classList.toggle('d-none');$('answerButton').textContent=visible?'Show answer':'Hide answer';panel.innerHTML='<div class="alert alert-info mb-0"><strong>Slowest → fastest:</strong><div class="answer-sequence mt-2">'+families.map(item=>`<span>${item.label}</span>`).join('<b aria-hidden="true">→</b>')+'</div></div>';}
function reset(){order=shuffle(correct);render();$('feedbackSection').classList.add('d-none');$('graphPanel').classList.add('d-none');$('answerPanel').classList.add('d-none');$('graphButton').textContent='Show graph';$('answerButton').textContent='Show answer';$('languageAnswer').value='';$('languageFeedback').innerHTML='';if(chart){chart.dispose();chart=null;}}
$('checkButton').addEventListener('click',check);$('shuffleButton').addEventListener('click',()=>{order=shuffle(correct);render();});$('resetButton').addEventListener('click',reset);$('graphButton').addEventListener('click',showGraph);$('answerButton').addEventListener('click',showAnswer);$('languageCheck').addEventListener('click',()=>{const value=$('languageAnswer').value;$('languageFeedback').innerHTML=value==='faster'?'<span class="text-success fw-semibold">Correct! For sufficiently large n, n² grows faster than n log₂n.</span>':value?'<span class="text-danger fw-semibold">Try again. Compare the ratio n²/(n log₂n).</span>':'<span class="text-secondary">Choose a phrase first.</span>';});window.addEventListener('resize',()=>chart?.resize());reset();localStorage.setItem('algorithmPlayground.lastModule','race');
