import './algorithms/index.js';
import {executeAlgorithm} from './core/algorithm-engine.js';
import {createCheckpointSession} from './core/decision-checkpoints.js';
import {renderCheckpoint,renderCheckpointFeedback} from './core/checkpoint-renderer.js';
import {runSchedulingRule,schedulingRules,isCompatible,depthAt,maximumDepth} from './core/interval-analysis.js';
import {intervalInstances,cloneInstance} from './data/interval-instances.js';
const $=id=>document.getElementById(id);let builder=cloneInstance().intervals,scheduleExecution,scheduleIndex=0,partitionExecution,partitionIndex=0;
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-view]').forEach(item=>item.classList.toggle('active',item===button));document.querySelectorAll('.lab-view').forEach(view=>view.classList.add('d-none'));$(`${button.dataset.view}View`).classList.remove('d-none');}));
for(const id of ['strategyInstance','scheduleInstance','partitionInstance'])intervalInstances.forEach(instance=>$(id).add(new Option(instance.name,instance.id)));
function instance(selectId){return cloneInstance($(selectId).value);}
function timeline(host,intervals,states={}){const end=Math.max(...intervals.map(item=>item.finish));host.innerHTML=intervals.map(item=>`<button type="button" class="interval-bar state-${states[item.id]??'UNSEEN'}" style="--start:${item.start};--span:${item.finish-item.start};--total:${end}" title="${item.id}: [${item.start}, ${item.finish})"><strong>${item.id}</strong><span>[${item.start}, ${item.finish})</span><small>${states[item.id]??'UNSEEN'}</small></button>`).join('');}
function compare(){const data=instance('strategyInstance');timeline($('strategyTimeline'),data.intervals);const results=Object.keys(schedulingRules).map(rule=>runSchedulingRule(data.intervals,rule));$('comparisonTable').innerHTML=`<div class="table-responsive"><table class="table"><thead><tr><th>Rule</th><th>Candidate order</th><th>Selected</th><th>Rejected</th><th>Cardinality</th></tr></thead><tbody>${results.map(result=>`<tr><td>${schedulingRules[result.ruleId].label}</td><td>${result.ordered.map(x=>x.id).join(' → ')}</td><td>${result.selected.map(x=>x.id).join(', ')}</td><td>${result.rejected.map(x=>x.id).join(', ')}</td><td>${result.cardinality}</td></tr>`).join('')}</tbody></table></div><p class="alert alert-info">Your prediction: <strong>${schedulingRules[$('predictionRule').value].label}</strong>. Compare the observed cardinalities; this instance is evidence, not a proof.</p>`;}
function renderBuilder(){ $('builderRows').innerHTML=builder.map((item,index)=>`<div class="builder-row"><strong>${item.id}</strong><input type="number" value="${item.start}" data-field="start" data-index="${index}" aria-label="${item.id} start"><input type="number" value="${item.finish}" data-field="finish" data-index="${index}" aria-label="${item.id} finish"><button class="btn btn-sm btn-outline-danger" data-delete="${index}" aria-label="Delete ${item.id}">×</button></div>`).join('');$('manualSelection').innerHTML='<strong>My compatible comparison set</strong>'+builder.map(item=>`<label class="d-block"><input type="checkbox" value="${item.id}"> ${item.id} [${item.start}, ${item.finish})</label>`).join('');}
$('builderRows').addEventListener('change',event=>{const input=event.target;if(input.dataset.field)builder[Number(input.dataset.index)][input.dataset.field]=Number(input.value);renderBuilder();});$('builderRows').addEventListener('click',event=>{const index=event.target.dataset.delete;if(index!==undefined){builder.splice(Number(index),1);renderBuilder();}});$('addInterval').addEventListener('click',()=>{if(builder.length>=8)return;builder.push({id:String.fromCharCode(65+builder.length),start:0,finish:1});renderBuilder();});
function testCounterexample(){const feedback=$('counterexampleFeedback');if(!builder.length||builder.some(x=>!Number.isFinite(x.start)||!Number.isFinite(x.finish)||x.start>=x.finish)){feedback.innerHTML='<div class="alert alert-warning">Every interval needs start &lt; finish.</div>';return;}const rule=runSchedulingRule(builder,$('challengeRule').value),chosenIds=[...$('manualSelection').querySelectorAll(':checked')].map(x=>x.value),chosen=builder.filter(x=>chosenIds.includes(x.id));if(!isCompatible(chosen)){feedback.innerHTML='<div class="alert alert-warning">Your comparison set is not compatible.</div>';return;}const success=chosen.length>rule.cardinality;feedback.innerHTML=`<div class="alert alert-${success?'success':'info'}">Rule selected ${rule.cardinality}; your set has ${chosen.length}. ${success?'Counterexample found.':'Not a counterexample yet.'}${$('challengeRule').value==='earliestFinish'&&!success?' Failed attempts do not prove correctness; continue to the exchange argument.':''}</div>`;}
function runSchedule(){scheduleExecution=executeAlgorithm('interval-scheduling',{intervals:instance('scheduleInstance').intervals});scheduleIndex=0;showSchedule();}
function showSchedule(){if(!scheduleExecution)return;const step=scheduleExecution.trace[scheduleIndex],selected=step.structures.selected??[],rejected=step.structures.rejected??[],states=Object.fromEntries([...selected.map(x=>[x.id,'SELECTED']),...rejected.map(x=>[x.id,'REJECTED'])]);if(step.visualization.currentInterval)states[step.visualization.currentInterval]=step.visualization.state??'CURRENT';timeline($('scheduleTimeline'),step.structures.ordered,states);$('scheduleStatus').innerHTML=`<strong>Step ${scheduleIndex+1}/${scheduleExecution.trace.length}</strong> · lastFinish = <code>${step.variables.lastFinish??'−∞'}</code> · ${step.message.en}`;$('candidateList').innerHTML=step.structures.ordered.map(x=>`<span class="candidate ${states[x.id]??''}">${x.id} [${x.start},${x.finish})</span>`).join('');renderCode('scheduleCode',[1,2,3,4,5,6],step.line);checkpointForSchedule(step);}
function checkpointForSchedule(step){const host=$('scheduleCheckpoint');host.innerHTML='';if(step.type!=='considerCandidate')return;const checkpoint={id:`ui-${step.variables.currentId}`,responseType:'accept-reject',prompt:{en:`Will ${step.variables.currentId} be selected?`},options:[{id:'accept',label:{en:'Select'}},{id:'reject',label:{en:'Reject'}}],validAnswers:[step.variables.compatible?'accept':'reject'],stateProjection:{values:{start:step.variables.start,lastFinish:step.variables.lastFinish??'−∞'}},hints:[{en:'Compare the current start with lastFinish.'}],explanation:{en:step.variables.compatible?'Its start is at least lastFinish, so it is compatible.':'Its start is before lastFinish, so it overlaps the last selection.'}};mountCheckpoint(host,checkpoint);}
function runPartition(){partitionExecution=executeAlgorithm('interval-partitioning',{intervals:instance('partitionInstance').intervals});partitionIndex=0;showPartition();updateDepth();}
function showPartition(){if(!partitionExecution)return;const step=partitionExecution.trace[partitionIndex],rooms=step.structures.rooms??[];$('partitionStatus').innerHTML=`<strong>Step ${partitionIndex+1}/${partitionExecution.trace.length}</strong> · rooms = ${step.variables.roomCount??rooms.length} · ${step.message.en}`;$('roomTimelines').innerHTML=rooms.length?rooms.map(room=>`<div class="room-row"><strong>${room.id}</strong><div class="candidate-list">${room.intervals.map(x=>`<span class="candidate SELECTED">${x.id} [${x.start},${x.finish})</span>`).join('')}</div></div>`).join(''):'<p class="text-secondary">No rooms yet.</p>';$('roomHeap').innerHTML=(step.structures.heap??[]).map((room,index)=>`<div class="heap-node"><small>${index===0?'MIN':''}</small><strong>${room.id}</strong><span>key ${room.key}</span></div>`).join('');checkpointForPartition(step);}
function checkpointForPartition(step){const host=$('partitionCheckpoint');host.innerHTML='';if(step.type!=='considerCandidate')return;const answer=step.variables.reuse?'accept':'reject',checkpoint={id:`partition-ui-${step.variables.currentId}`,responseType:'accept-reject',prompt:{en:`Reuse the earliest available room for ${step.variables.currentId}, or create one?`},options:[{id:'accept',label:{en:'Reuse room'}},{id:'reject',label:{en:'Create room'}}],validAnswers:[answer],stateProjection:{values:{start:step.variables.start,minFinish:step.variables.minFinish??'none'}},hints:[{en:'Reuse is possible only when start ≥ minFinish.'}],explanation:{en:step.variables.reuse?'The minimum-finish room is available.':'All existing rooms are occupied at this start time, so a new room is unavoidable.'}};mountCheckpoint(host,checkpoint);}
function mountCheckpoint(host,checkpoint){const session=createCheckpointSession(checkpoint);renderCheckpoint(host,checkpoint,{onSubmit:(response,node)=>renderCheckpointFeedback(node,session.submit(response)),onHint:node=>renderCheckpointFeedback(node,session.hint()),onReveal:node=>renderCheckpointFeedback(node,session.reveal())});}
function renderCode(id,lines,active){$(id).innerHTML=lines.map(line=>`<li class="${line===active?'active':''}"><code>${line}</code> ${['order by finish','S ← ∅; lastFinish ← −∞','for each candidate','if start ≥ lastFinish','select; update lastFinish','reject'][line-1]}</li>`).join('');}
function updateDepth(){const data=instance('partitionInstance'),time=Number($('depthTime').value),active=data.intervals.filter(x=>x.start<=time&&time<x.finish),depth=depthAt(data.intervals,time),maximum=maximumDepth(data.intervals);$('depthResult').innerHTML=`<p>At <strong>t = ${time}</strong>: ${active.map(x=>x.id).join(', ')||'no intervals'} · depth <strong>${depth}</strong>.</p><p class="alert alert-${depth===maximum?'success':'info'} mb-0">${depth===maximum?`Witness found: ${depth} simultaneous intervals require at least ${depth} rooms.`:`Maximum depth is ${maximum}; keep searching for a witness.`}</p>`;}
function move(kind,delta){if(kind==='schedule'&&scheduleExecution){scheduleIndex=Math.max(0,Math.min(scheduleExecution.trace.length-1,scheduleIndex+delta));showSchedule();}if(kind==='partition'&&partitionExecution){partitionIndex=Math.max(0,Math.min(partitionExecution.trace.length-1,partitionIndex+delta));showPartition();}}
$('compareRules').addEventListener('click',compare);$('testCounterexample').addEventListener('click',testCounterexample);$('runSchedule').addEventListener('click',runSchedule);$('schedulePrev').addEventListener('click',()=>move('schedule',-1));$('scheduleNext').addEventListener('click',()=>move('schedule',1));$('runPartition').addEventListener('click',runPartition);$('partitionPrev').addEventListener('click',()=>move('partition',-1));$('partitionNext').addEventListener('click',()=>move('partition',1));$('depthTime').addEventListener('input',updateDepth);$('partitionInstance').addEventListener('change',updateDepth);$('checkExchange').addEventListener('click',()=>{const properties=[...$('exchangeView').querySelectorAll('fieldset :checked')].map(x=>x.value).sort().join(','),correct=$('exchangeOut').value==='A'&&$('exchangeIn').value==='B'&&properties==='agreement,cardinality,feasibility';$('exchangeFeedback').innerHTML=`<div class="alert alert-${correct?'success':'warning'}">${correct?'Correct: feasibility and cardinality remain, and agreement grows by one position.':'Revisit the first disagreement and select exactly the three preserved properties.'}</div>`;});
renderBuilder();compare();updateDepth();
