import { ExpressionError, parseFunction, safeEvaluate, generateRange, formatLargeNumber } from './math-utils.js';

const $=id=>document.getElementById(id);
const challenges={
  initial:{title:'Ejemplo inicial: cuadrado perfecto',f:'n^2 + 2*n + 1',g:'n^2',c:4,k:1,range:100},
  linear:{title:'Desafío lineal',f:'3*n + 2',g:'n',c:1,k:1,range:100},
  quadratic:{title:'Desafío cuadrático',f:'5*n^2 + 3*n + 7',g:'n^2',c:2,k:1,range:100},
  cubic:{title:'Desafío cúbico',f:'2*n^3 + n',g:'n^3',c:1,k:1,range:100},
  impossible:{title:'Impossible challenge: busca dónde falla',f:'n^2',g:'n',c:10,k:1,range:100}
};
let chart=null, parsedF=null, parsedG=null, hasRun=false;

function showMessage(kind,text){const box=$('message');box.className=`alert alert-${kind}`;box.textContent=text;}
function clearMessage(){$('message').className='alert d-none';$('message').textContent='';}
function syncPair(source,target){$(target).value=$(source).value;invalidate();}
function invalidate(){if(!hasRun)return;$('runButton').textContent='Run experiment again';showMessage('info','Los parámetros cambiaron. Ejecuta de nuevo para actualizar el resultado.');}
function parseInputs(){try{parsedF=parseFunction($('functionF').value);parsedG=parseFunction($('functionG').value);return true;}catch(error){showMessage('danger',error instanceof ExpressionError?`No fue posible interpretar la expresión. ${error.message}`:error.message);return false;}}
function readParameters(){const c=Number($('cInput').value),k=Number($('kInput').value),range=Number($('testRange').value);if(!Number.isFinite(c)||c<=0||c>20)throw new RangeError('C debe estar entre 0.1 y 20.');if(!Number.isInteger(k)||k<0||k>100)throw new RangeError('k debe ser un entero entre 0 y 100.');return{c,k,range};}
function findCounterexample(c,k,range){for(let n=Math.max(0,k+1);n<=range;n++){const f=safeEvaluate(parsedF,n),cg=c*safeEvaluate(parsedG,n);if(!Number.isFinite(f)||!Number.isFinite(cg)||f>cg)return{n,f,cg};}return null;}
function plot(c,k,range){const min=0,plotMax=Math.min(range,1000),ns=generateRange(min,plotMax,Math.min(300,plotMax+1));const f=ns.map(n=>[n,finiteOrNull(safeEvaluate(parsedF,n))]);const cg=ns.map(n=>[n,finiteOrNull(c*safeEvaluate(parsedG,n))]);$('chartEmpty').classList.add('d-none');$('witnessChart').classList.remove('d-none');if(!chart)chart=echarts.init($('witnessChart'));chart.setOption({animation:false,color:['#2457c5','#d2642a'],tooltip:{trigger:'axis'},legend:{top:4},grid:{left:70,right:30,top:50,bottom:65},xAxis:{type:'value',name:'n',nameLocation:'middle',nameGap:32,max:plotMax},yAxis:{type:'value',name:'valor'},dataZoom:[{type:'inside'},{type:'slider',bottom:10}],series:[{name:'f(n)',type:'line',showSymbol:false,data:f,markLine:{silent:true,symbol:'none',label:{formatter:`k = ${k}`},lineStyle:{color:'#6b7280',type:'dashed'},data:[{xAxis:k}]}},{name:'C·g(n)',type:'line',showSymbol:false,data:cg}]},true);}
function finiteOrNull(value){return Number.isFinite(value)?value:null;}
function run(){clearMessage();if(!parseInputs())return;let params;try{params=readParameters();}catch(error){showMessage('danger',error.message);return;}const counterexample=findCounterexample(params.c,params.k,params.range);plot(params.c,params.k,params.range);$('observe').classList.remove('d-none');$('explain').classList.remove('d-none');if(counterexample){$('witnessResult').innerHTML=`<div class="alert alert-danger mb-0"><strong>✗ Counterexample found</strong><br>n = ${counterexample.n}<br>f(n) = ${formatLargeNumber(counterexample.f)}<br>C·g(n) = ${formatLargeNumber(counterexample.cg)}</div>`;}else{$('witnessResult').innerHTML=`<div class="alert alert-success mb-0"><strong>✓ The inequality holds for all integer n &gt; k in the tested range.</strong><br>Comprobado desde n = ${params.k+1} hasta n = ${params.range}.</div>`;}showMessage(counterexample?'warning':'success',counterexample?'Tu predicción ya puede contrastarse con el contraejemplo.':'Tu predicción ya puede contrastarse con el rango comprobado.');$('runButton').textContent='Check again';hasRun=true;localStorage.setItem('algorithmPlayground.lastModule','witnesses');}
function applyChallenge(key){const item=challenges[key];$('challengeSelect').value=key;$('challengeTitle').textContent=item.title;$('functionF').value=item.f;$('functionG').value=item.g;$('cInput').value=$('cSlider').value=item.c;$('kInput').value=$('kSlider').value=item.k;$('testRange').value=String(item.range);document.querySelectorAll('[name=witnessPrediction]').forEach(x=>x.checked=false);$('runButton').disabled=true;$('predictionHint').textContent='Selecciona una opción para habilitar la comprobación.';resetResult();}
function resetResult(){hasRun=false;$('observe').classList.add('d-none');$('explain').classList.add('d-none');$('witnessChart').classList.add('d-none');$('chartEmpty').classList.remove('d-none');$('witnessResult').innerHTML='';$('runButton').textContent='Check prediction';if(chart){chart.dispose();chart=null;}clearMessage();}
function reset(){applyChallenge('initial');document.querySelectorAll('[name=witnessPrediction]').forEach(x=>x.checked=false);$('runButton').disabled=true;$('predictionHint').textContent='Selecciona una opción para habilitar la comprobación.';}
function increaseRange(){const values=[100,1000,10000,100000],current=Number($('testRange').value),next=values[Math.min(values.indexOf(current)+1,values.length-1)];$('testRange').value=String(next);invalidate();if(next===current)showMessage('secondary','Ya estás usando el rango máximo de 100,000.');}
function applyUrl(){const params=new URLSearchParams(location.search);if(params.has('f'))$('functionF').value=params.get('f').slice(0,160);if(params.has('g'))$('functionG').value=params.get('g').slice(0,160);}
document.querySelectorAll('[name=witnessPrediction]').forEach(input=>input.addEventListener('change',()=>{$('runButton').disabled=false;$('predictionHint').textContent='Predicción registrada. Ya puedes comprobar los testigos.';}));
$('cSlider').addEventListener('input',()=>syncPair('cSlider','cInput'));$('cInput').addEventListener('input',()=>syncPair('cInput','cSlider'));$('kSlider').addEventListener('input',()=>syncPair('kSlider','kInput'));$('kInput').addEventListener('input',()=>syncPair('kInput','kSlider'));
['functionF','functionG','testRange'].forEach(id=>$(id).addEventListener('change',invalidate));$('runButton').addEventListener('click',run);$('resetButton').addEventListener('click',reset);$('increaseRange').addEventListener('click',increaseRange);$('challengeSelect').addEventListener('change',()=>applyChallenge($('challengeSelect').value));$('newChallenge').addEventListener('click',()=>{const keys=Object.keys(challenges).filter(k=>k!==$('challengeSelect').value);applyChallenge(keys[Math.floor(Math.random()*keys.length)]);});window.addEventListener('resize',()=>chart?.resize());applyUrl();
