export const RECURSIVE_EVENT_TYPES=Object.freeze(['callCreated','callActivated','baseCaseChecked','baseCaseReached','problemDivided','childCallStarted','childCallReturned','combineStarted','combineStep','combineCompleted','callReturned']);

export function createRecursiveTraceRecorder(algorithm){
  const frames=new Map(),stack=[],trace=[];
  function addFrame(frame){if(frames.has(frame.frameId))throw new Error(`Duplicate frame: ${frame.frameId}`);frames.set(frame.frameId,{algorithm,status:'pending',localVariables:{},childFrameIds:[],returnValue:null,...structuredClone(frame)});}
  function updateFrame(frameId,changes){const frame=frames.get(frameId);if(!frame)throw new RangeError(`Unknown frame: ${frameId}`);Object.assign(frame,structuredClone(changes));}
  function push(frameId){if(stack.includes(frameId))throw new Error(`Frame already active: ${frameId}`);stack.push(frameId);updateFrame(frameId,{status:'active'});}
  function pop(frameId,returnValue){if(stack.at(-1)!==frameId)throw new Error(`Can only return the active frame: ${frameId}`);stack.pop();updateFrame(frameId,{status:'returned',returnValue});const parent=frames.get(frameId).parentFrameId;if(parent&&frames.has(parent))updateFrame(parent,{status:'active'});}
  function record(event){if(!RECURSIVE_EVENT_TYPES.includes(event.type))throw new RangeError(`Unknown recursive event: ${event.type}`);const snapshot={step:trace.length+1,algorithm,type:event.type,line:event.line??null,frameId:event.frameId??stack.at(-1)??null,childFrameId:event.childFrameId??null,variables:structuredClone(event.variables??{}),structures:{callStack:[...stack],frames:[...frames.values()].map(frame=>structuredClone(frame))},visualization:structuredClone(event.visualization??{}),checkpointId:event.checkpointId??null,message:structuredClone(event.message??{en:'',es:''})};trace.push(deepFreeze(snapshot));return snapshot;}
  return {addFrame,updateFrame,push,pop,record,getFrame:id=>structuredClone(frames.get(id)),get trace(){return Object.freeze([...trace]);}};
}

export function buildSplitAndCombineTrace(values){
  if(!Array.isArray(values)||values.length===0||!values.every(Number.isFinite))throw new RangeError('The anatomy trace requires a nonempty numeric array.');
  const recorder=createRecursiveTraceRecorder('split-and-sum');
  function visit(segment,start,parentFrameId=null,path='root',depth=0){const frameId=`sum-${path}`,end=start+segment.length;recorder.addFrame({frameId,parentFrameId,depth,input:{values:[...segment],range:[start,end]}});if(parentFrameId){const parent=recorder.getFrame(parentFrameId);recorder.updateFrame(parentFrameId,{childFrameIds:[...parent.childFrameIds,frameId],status:'waiting'});}recorder.record({type:'callCreated',frameId,variables:{size:segment.length},visualization:{activeRange:[start,end]},message:msg(`Create a call for [${segment.join(', ')}].`)});recorder.push(frameId);recorder.record({type:'callActivated',frameId,checkpointId:`next-${frameId}`,variables:{size:segment.length},visualization:{activeRange:[start,end]},message:msg(`Activate ${frameId}.`)});const base=segment.length===1;recorder.record({type:'baseCaseChecked',frameId,variables:{size:segment.length,isBaseCase:base},visualization:{activeRange:[start,end]},message:msg(base?'The segment is a base case.':'The segment must be divided.')});if(base){const value=segment[0];recorder.record({type:'baseCaseReached',frameId,checkpointId:`base-${frameId}`,variables:{returnValue:value},visualization:{activeRange:[start,end]},message:msg(`A singleton returns ${value}.`)});recorder.pop(frameId,value);recorder.record({type:'callReturned',frameId,variables:{returnValue:value},visualization:{completedRange:[start,end]},message:msg(`${frameId} returns ${value}.`)});return value;}
    const mid=Math.floor(segment.length/2),left=segment.slice(0,mid),right=segment.slice(mid);recorder.updateFrame(frameId,{status:'active',localVariables:{mid:start+mid}});recorder.record({type:'problemDivided',frameId,checkpointId:`divide-${frameId}`,variables:{leftSize:left.length,rightSize:right.length,mid:start+mid},visualization:{activeRange:[start,end],leftRange:[start,start+mid],rightRange:[start+mid,end]},message:msg(`Divide into sizes ${left.length} and ${right.length}.`)});recorder.record({type:'childCallStarted',frameId,childFrameId:`sum-${path}-L`,variables:{side:'left'},message:msg('Start the left recursive call.')});const leftValue=visit(left,start,frameId,`${path}-L`,depth+1);recorder.record({type:'childCallReturned',frameId,childFrameId:`sum-${path}-L`,checkpointId:`after-left-${frameId}`,variables:{leftValue,nextEvent:'right-call'},message:msg(`The left child returned ${leftValue}; the right child is next.`)});recorder.updateFrame(frameId,{status:'waiting',localVariables:{mid:start+mid,leftValue}});recorder.record({type:'childCallStarted',frameId,childFrameId:`sum-${path}-R`,variables:{side:'right'},message:msg('Start the right recursive call.')});const rightValue=visit(right,start+mid,frameId,`${path}-R`,depth+1);recorder.updateFrame(frameId,{status:'active',localVariables:{mid:start+mid,leftValue,rightValue}});recorder.record({type:'childCallReturned',frameId,childFrameId:`sum-${path}-R`,checkpointId:`combine-ready-${frameId}`,variables:{leftValue,rightValue,nextEvent:'combine'},message:msg(`Both children have returned; ${frameId} can combine.`)});recorder.updateFrame(frameId,{status:'combining'});recorder.record({type:'combineStarted',frameId,variables:{leftValue,rightValue},message:msg('Begin combining the two return values.')});const result=leftValue+rightValue;recorder.record({type:'combineStep',frameId,variables:{leftValue,rightValue,result},message:msg(`${leftValue} + ${rightValue} = ${result}.`)});recorder.record({type:'combineCompleted',frameId,checkpointId:`return-${frameId}`,variables:{returnValue:result},message:msg(`Combination completed with ${result}.`)});recorder.pop(frameId,result);recorder.record({type:'callReturned',frameId,variables:{returnValue:result},visualization:{completedRange:[start,end]},message:msg(`${frameId} returns ${result}.`)});return result;}
  const result=visit([...values],0);return deepFreeze({algorithm:'split-and-sum',input:[...values],result,trace:[...recorder.trace]});
}
function msg(en){return {en,es:en};}function deepFreeze(value){if(!value||typeof value!=='object'||Object.isFrozen(value))return value;Object.freeze(value);Object.values(value).forEach(deepFreeze);return value;}
