export const dijkstraAlgorithm={
  id:'dijkstra',name:{es:'Caminos mínimos de Dijkstra',en:"Dijkstra's Shortest Paths"},category:'greedy',inputType:'weighted-graph',parameters:['vertices','edges','source'],supportedOperations:['comparisons','assignments','arithmeticOperations','arrayAccesses','loopIterations'],
  pseudocode:[{id:1,text:'d[source] ← 0; d[v] ← ∞ for v ≠ source'},{id:2,text:'Q ← all vertices keyed by d'},{id:3,text:'while Q is not empty'},{id:4,text:'    u ← extractMin(Q); add u to S'},{id:5,text:'    for each edge (u,v)'},{id:6,text:'        candidate ← d[u] + w(u,v)'},{id:7,text:'        if candidate < d[v]'},{id:8,text:'            d[v] ← candidate; pred[v] ← u; decreaseKey'}],
  generateInput(input={}){return normalize(input);},
  execute(input,_options,recorder){const graph=normalize(input);if(graph.edges.some(edge=>edge.weight<0))throw new RangeError('Standard Dijkstra requires nonnegative edge weights.');const distances=Object.fromEntries(graph.vertices.map(v=>[v.id,v.id===graph.source?0:Infinity])),predecessors=Object.fromEntries(graph.vertices.map(v=>[v.id,null])),fixed=[];let queue=graph.vertices.map(v=>v.id);
    record(recorder,1,'assignment',{source:graph.source},{distances,predecessors,fixed,queue:queueView(queue,distances)}, {},{assignments:graph.vertices.length+1},'Initialize tentative distances; pred[v] stores a predecessor vertex.');
    while(queue.length){const minimum=Math.min(...queue.map(id=>distances[id])),ties=queue.filter(id=>distances[id]===minimum).sort(),u=ties[0];record(recorder,4,'checkpoint',{minimum,tiedVertices:ties},{distances,predecessors,fixed,queue:queueView(queue,distances)},{activeVertex:u},{comparisons:Math.max(0,queue.length-1)},`The minimum queue key is ${format(minimum)}.`,`dijkstra-extract-${fixed.length}`);queue=queue.filter(id=>id!==u);fixed.push(u);record(recorder,4,'extractMin',{u,distanceU:distances[u]},{distances,predecessors,fixed,queue:queueView(queue,distances)},{activeVertex:u},{assignments:2,arrayAccesses:1},`Fix ${u} with distance ${format(distances[u])}.`);
      if(distances[u]===Infinity)continue;const outgoing=graph.edges.flatMap(edge=>neighbors(edge,u,graph.directed)).filter(item=>queue.includes(item.v)),updates=[];for(const edge of outgoing){const candidate=distances[u]+edge.weight,oldDistance=distances[edge.v],changes=candidate<oldDistance;if(changes)updates.push(edge.v);record(recorder,7,'relaxEdge',{u,v:edge.v,distanceU:distances[u],edgeWeight:edge.weight,oldDistanceV:oldDistance,candidateDistance:candidate,changes},{distances,predecessors,fixed,queue:queueView(queue,distances)},{activeVertex:u,activeEdge:edge.id,comparedVertex:edge.v},{comparisons:1,arithmeticOperations:1,arrayAccesses:3,loopIterations:1},changes?`${candidate} improves d[${edge.v}].`:`Keep d[${edge.v}] = ${format(oldDistance)}.`,`dijkstra-relax-${u}-${edge.v}`);if(changes){distances[edge.v]=candidate;predecessors[edge.v]=u;record(recorder,8,'decreaseKey',{u,v:edge.v,newDistance:candidate,newPredecessor:u},{distances,predecessors,fixed,queue:queueView(queue,distances)},{activeVertex:u,activeEdge:edge.id,comparedVertex:edge.v},{assignments:2,arrayAccesses:2},`Update d[${edge.v}] and pred[${edge.v}].`);}}
      record(recorder,5,'checkpoint',{u,changedNeighbors:updates},{distances,predecessors,fixed,queue:queueView(queue,distances)},{activeVertex:u},{},`Relaxation from ${u} is complete.`,`dijkstra-changes-${u}`);
    }return {distances,predecessors,fixedOrder:fixed};
  }
};
function normalize(input){const vertices=(input.vertices??[]).map((v,index)=>typeof v==='string'?{id:v,x:20+index*15,y:50}:{...v,id:String(v.id)}),ids=new Set(vertices.map(v=>v.id)),source=String(input.source??vertices[0]?.id??'');if(!vertices.length||ids.size!==vertices.length||!ids.has(source))throw new RangeError('Dijkstra requires unique vertices and a valid source.');const edges=(input.edges??[]).map((edge,index)=>({id:String(edge.id??`e${index+1}`),from:String(edge.from),to:String(edge.to),weight:Number(edge.weight)}));if(edges.some(edge=>!ids.has(edge.from)||!ids.has(edge.to)||!Number.isFinite(edge.weight)))throw new RangeError('Every edge requires valid endpoints and a finite weight.');return {vertices,edges,source,directed:input.directed!==false};}
function neighbors(edge,u,directed){if(edge.from===u)return [{...edge,v:edge.to}];if(!directed&&edge.to===u)return [{...edge,v:edge.from}];return [];}
function queueView(queue,distances){return queue.map(vertex=>({vertex,key:distances[vertex]})).sort((a,b)=>a.key-b.key||a.vertex.localeCompare(b.vertex));}
function record(recorder,line,type,variables,structures,visualization,increment,message,checkpointId=null){recorder.record({line,type,variables,structures:{...structures,distances:{...structures.distances},predecessors:{...structures.predecessors},fixed:[...structures.fixed],queue:structures.queue.map(item=>({...item}))},visualization,increment,message:{en:message,es:message},checkpointId});}
function format(value){return value===Infinity?'∞':value;}
