export const inversionCountAlgorithm={
  id:'inversion-count',name:{es:'Conteo de inversiones',en:'Sort and Count Inversions'},category:'divide-and-conquer',inputType:'numeric-array',parameters:['array'],supportedOperations:['comparisons','assignments','arithmeticOperations','arrayAccesses','loopIterations'],
  pseudocode:[{id:1,text:'SortAndCount(A[l:r])'},{id:2,text:'if size ≤ 1: return (A[l:r], 0)'},{id:3,text:'split at floor(size/2)'},{id:4,text:'(L,rL) ← SortAndCount(left)'},{id:5,text:'(R,rR) ← SortAndCount(right)'},{id:6,text:'(C,rCross) ← MergeAndCount(L,R)'},{id:7,text:'if L[i] ≤ R[j]: copy L[i]'},{id:8,text:'else copy R[j]; rCross += |L| − i'},{id:9,text:'return (C, rL + rR + rCross)'}],
  generateInput({array=[]}={}){return {array:validate(array)};},
  execute(input,_options,recorder){const original=validate(input.array),display=[...original],frames=new Map(),stack=[],metrics={recursiveCalls:0,mergeOperations:0,copies:0,maxDepth:0,crossingInversions:0};
    const emit=(line,type,frameId,extra={})=>recorder.record({line,type,frameId,childFrameId:extra.childFrameId??null,variables:extra.variables??{},structures:{callStack:[...stack],frames:[...frames.values()].map(frame=>structuredClone(frame)),array:[...display],metrics:{...metrics},merge:extra.merge?structuredClone(extra.merge):null,counts:extra.counts?{...extra.counts}:null},visualization:extra.visualization??{},checkpointId:extra.checkpointId??null,increment:extra.increment??{},message:{en:extra.message??'',es:extra.message??''}});
    function visit(segment,start,parentFrameId=null,path='root',depth=0){const frameId=`count-${path}`,end=start+segment.length,frame={frameId,parentFrameId,algorithm:'inversion-count',depth,status:'pending',input:{values:[...segment],range:[start,end]},localVariables:{},childFrameIds:[],returnValue:null};frames.set(frameId,frame);if(parentFrameId){const parent=frames.get(parentFrameId);parent.childFrameIds.push(frameId);parent.status='waiting';}metrics.recursiveCalls++;metrics.maxDepth=Math.max(metrics.maxDepth,depth);emit(1,'callCreated',frameId,{variables:{size:segment.length},message:`Create ${frameId}.`});stack.push(frameId);frame.status='active';emit(1,'callActivated',frameId,{variables:{size:segment.length},visualization:{activeRange:[start,end]},message:`Activate ${frameId}.`});const base=segment.length<=1;emit(2,'baseCaseChecked',frameId,{variables:{isBaseCase:base,size:segment.length},message:base?'Return the already sorted base case.':'Divide and count both halves.'});if(base){const result={sorted:[...segment],count:0};stack.pop();frame.status='returned';frame.returnValue=structuredClone(result);emit(2,'callReturned',frameId,{variables:{returnValue:result},visualization:{completedRange:[start,end]},message:`Return ([${segment.join(', ')}], 0).`});if(parentFrameId)frames.get(parentFrameId).status='active';return result;}
      const mid=Math.floor(segment.length/2),leftInput=segment.slice(0,mid),rightInput=segment.slice(mid);frame.localVariables.mid=start+mid;emit(3,'problemDivided',frameId,{variables:{left:leftInput,right:rightInput},visualization:{activeRange:[start,end],leftRange:[start,start+mid],rightRange:[start+mid,end]},checkpointId:`inversion-divide-${frameId}`,message:'Divide inversions into left, right, and crossing categories.'});emit(4,'childCallStarted',frameId,{childFrameId:`count-${path}-L`,message:'Count the left half.'});const leftResult=visit(leftInput,start,frameId,`${path}-L`,depth+1);emit(4,'childCallReturned',frameId,{childFrameId:`count-${path}-L`,variables:{leftCount:leftResult.count},message:`Left count is ${leftResult.count}.`});frame.status='waiting';emit(5,'childCallStarted',frameId,{childFrameId:`count-${path}-R`,message:'Count the right half.'});const rightResult=visit(rightInput,start+mid,frameId,`${path}-R`,depth+1);frame.status='combining';metrics.mergeOperations++;const left=leftResult.sorted,right=rightResult.sorted;let i=0,j=0,crossing=0,output=[];const counts=()=>({left:leftResult.count,right:rightResult.count,crossing,total:leftResult.count+rightResult.count+crossing});emit(6,'combineStarted',frameId,{variables:{i,j},merge:{left,right,i,j,output},counts:counts(),message:'Begin MergeAndCount with two sorted lists.'});
      while(i<left.length||j<right.length){if(i>=left.length||j>=right.length){const chosen=i>=left.length?right[j++]:left[i++];output.push(chosen);metrics.copies++;emit(7,'combineStep',frameId,{variables:{chosen,increment:0,i,j},merge:{left,right,i,j,output},counts:counts(),increment:{assignments:1,arrayAccesses:1,loopIterations:1},message:`Copy remaining value ${chosen}; no new inversion.`});continue;}const leftValue=left[i],rightValue=right[j],beforeI=i,beforeJ=j;if(leftValue<=rightValue){output.push(leftValue);i++;metrics.copies++;emit(7,'combineStep',frameId,{variables:{leftValue,rightValue,chosen:leftValue,advance:'i',increment:0,i:beforeI,j:beforeJ},merge:{left,right,i:beforeI,j:beforeJ,output},counts:counts(),checkpointId:`inversion-no-increment-${frameId}-${output.length}`,increment:{comparisons:1,assignments:1,arrayAccesses:3,loopIterations:1},message:`Copy ${leftValue} from L; equal values are not inversions.`});}else{const increment=left.length-i,newPairs=left.slice(i).map(value=>[value,rightValue]);output.push(rightValue);j++;crossing+=increment;metrics.crossingInversions+=increment;metrics.copies++;emit(8,'crossingInversionsCounted',frameId,{variables:{leftValue,rightValue,chosen:rightValue,advance:'j',increment,remainingLeft:left.length-beforeI,newPairs,i:beforeI,j:beforeJ},merge:{left,right,i:beforeI,j:beforeJ,output},counts:counts(),checkpointId:`inversion-increment-${frameId}-${output.length}`,increment:{comparisons:1,assignments:1,arithmeticOperations:1,arrayAccesses:3,loopIterations:1},message:`Copy ${rightValue}; count ${increment} crossing inversion${increment===1?'':'s'}.`});}}
      const total=leftResult.count+rightResult.count+crossing;for(let offset=0;offset<output.length;offset++)display[start+offset]=output[offset];frame.returnValue={sorted:[...output],count:total};emit(9,'combineCompleted',frameId,{variables:{leftCount:leftResult.count,rightCount:rightResult.count,crossingCount:crossing,total,returnValue:frame.returnValue},merge:{left,right,i,j,output},counts:counts(),checkpointId:`inversion-total-${frameId}`,visualization:{completedRange:[start,end]},message:`Combine counts: ${leftResult.count} + ${rightResult.count} + ${crossing} = ${total}.`});stack.pop();frame.status='returned';emit(9,'callReturned',frameId,{variables:{returnValue:frame.returnValue},message:`${frameId} returns a sorted list and count ${total}.`});if(parentFrameId)frames.get(parentFrameId).status='active';return structuredClone(frame.returnValue);}
    return visit(original,0);
  }
};
function validate(array){if(!Array.isArray(array)||!array.every(Number.isFinite))throw new RangeError('Inversion Counting requires a numeric array.');return [...array];}
