export const kruskalAlgorithm={
  id:'kruskal',name:{es:'Árbol de expansión mínima de Kruskal',en:"Kruskal's Minimum Spanning Tree"},category:'greedy',inputType:'undirected-weighted-graph',parameters:['vertices','edges'],supportedOperations:['comparisons','assignments','arrayAccesses','loopIterations'],
  pseudocode:[{id:1,text:'sort edges by nondecreasing weight'},{id:2,text:'make one component per vertex'},{id:3,text:'for each edge (u,v) in order'},{id:4,text:'    if find(u) ≠ find(v)'},{id:5,text:'        accept edge; union components'},{id:6,text:'    else reject edge: it closes a cycle'},{id:7,text:'stop when |T| = |V| − 1'}],
  generateInput(input={}){return normalize(input);},
  execute(input,_options,recorder){const graph=normalize(input),ordered=[...graph.edges].sort((a,b)=>a.weight-b.weight||a.id.localeCompare(b.id)),components=Object.fromEntries(graph.vertices.map(v=>[v.id,v.id])),accepted=[],rejected=[];let totalWeight=0;
    emit(recorder,2,'assignment',{},{ordered,components,accepted,rejected,totalWeight},{},{assignments:graph.vertices.length},'Sort edges and create singleton components.');
    for(let index=0;index<ordered.length&&accepted.length<graph.vertices.length-1;index++){const edge=ordered[index],componentU=components[edge.from],componentV=components[edge.to],accept=componentU!==componentV,cyclePath=accept?[]:findPath(accepted,edge.from,edge.to);emit(recorder,4,'considerCandidate',{edgeId:edge.id,u:edge.from,v:edge.to,weight:edge.weight,componentU,componentV,accept,cyclePath},{ordered,components,accepted,rejected,totalWeight},{activeEdge:edge.id},{comparisons:1,arrayAccesses:2,loopIterations:1},accept?`${edge.id} connects distinct components.`:`${edge.id} would close a cycle.`,`kruskal-decision-${edge.id}`);if(accept){accepted.push(edge);totalWeight+=edge.weight;const old=componentV;for(const vertex of Object.keys(components))if(components[vertex]===old)components[vertex]=componentU;emit(recorder,5,'unionComponents',{edgeId:edge.id,componentU,componentV},{ordered,components,accepted,rejected,totalWeight},{activeEdge:edge.id},{assignments:2+Object.keys(components).length,arrayAccesses:2},`Accept ${edge.id} and union the components.`);}else{rejected.push(edge);emit(recorder,6,'rejectCycle',{edgeId:edge.id,cyclePath},{ordered,components,accepted,rejected,totalWeight},{activeEdge:edge.id,cycleEdges:[...cyclePath,edge.id]},{},`Reject ${edge.id}; path ${cyclePath.join(' → ')} plus this edge is a cycle.`);}}
    if(accepted.length!==graph.vertices.length-1)throw new RangeError('Kruskal requires a connected graph.');emit(recorder,7,'return',{selectedCount:accepted.length},{ordered,components,accepted,rejected,totalWeight},{},{},'Stop after selecting |V| − 1 edges.');return {edges:accepted.map(e=>e.id),rejected:rejected.map(e=>e.id),totalWeight,components};
  }
};
function normalize(input){const vertices=(input.vertices??[]).map(v=>typeof v==='string'?{id:v}:{...v,id:String(v.id)}),ids=new Set(vertices.map(v=>v.id));if(!vertices.length||ids.size!==vertices.length||input.directed===true)throw new RangeError('Kruskal requires unique vertices and an undirected graph.');const edges=(input.edges??[]).map((e,i)=>({id:String(e.id??`e${i+1}`),from:String(e.from),to:String(e.to),weight:Number(e.weight)}));if(edges.some(e=>!ids.has(e.from)||!ids.has(e.to)||!Number.isFinite(e.weight)))throw new RangeError('Invalid edge.');return {vertices,edges};}
function findPath(edges,start,target){const queue=[[start,[]]],seen=new Set([start]);while(queue.length){const [u,path]=queue.shift();if(u===target)return path;for(const edge of edges){const v=edge.from===u?edge.to:edge.to===u?edge.from:null;if(v&&!seen.has(v)){seen.add(v);queue.push([v,[...path,edge.id]]);}}}return [];}
function emit(recorder,line,type,variables,s,visualization,increment,message,checkpointId=null){recorder.record({line,type,variables,structures:{ordered:s.ordered.map(e=>({...e})),components:{...s.components},accepted:s.accepted.map(e=>({...e})),rejected:s.rejected.map(e=>({...e})),totalWeight:s.totalWeight},visualization,increment,message:{en:message,es:message},checkpointId});}
