export const mergeSortAlgorithm={
  id:'merge-sort',name:{es:'Ordenamiento por mezcla',en:'Merge Sort'},category:'divide-and-conquer',inputType:'numeric-array',parameters:['array'],supportedOperations:['comparisons','assignments','arrayAccesses','loopIterations'],
  pseudocode:[{id:1,text:'MergeSort(A[l:r])'},{id:2,text:'if r − l ≤ 1: return A[l:r]'},{id:3,text:'mid ← l + floor((r − l)/2)'},{id:4,text:'L ← MergeSort(A[l:mid])'},{id:5,text:'R ← MergeSort(A[mid:r])'},{id:6,text:'return Merge(L,R)'},{id:7,text:'compare L[i] and R[j]'},{id:8,text:'copy the smaller value; on ties copy L[i]'},{id:9,text:'copy the remaining suffix'}],
  generateInput({array=[]}={}){return {array:validate(array)};},
  execute(input,_options,recorder){const original=validate(input.array),display=[...original],frames=new Map(),stack=[],metrics={recursiveCalls:0,mergeOperations:0,copies:0,maxDepth:0};
    const emit=(line,type,frameId,extra={})=>recorder.record({line,type,frameId,childFrameId:extra.childFrameId??null,variables:extra.variables??{},structures:{callStack:[...stack],frames:[...frames.values()].map(copyFrame),array:[...display],metrics:{...metrics},merge:extra.merge?structuredClone(extra.merge):null},visualization:extra.visualization??{},checkpointId:extra.checkpointId??null,increment:extra.increment??{},message:{en:extra.message??'',es:extra.message??''}});
    function sort(segment,start,parentFrameId=null,path='root',depth=0){const frameId=`merge-${path}`,end=start+segment.length,frame={frameId,parentFrameId,algorithm:'merge-sort',depth,status:'pending',input:{values:[...segment],range:[start,end]},localVariables:{},childFrameIds:[],returnValue:null};frames.set(frameId,frame);if(parentFrameId){const parent=frames.get(parentFrameId);parent.childFrameIds.push(frameId);parent.status='waiting';}metrics.recursiveCalls++;metrics.maxDepth=Math.max(metrics.maxDepth,depth);emit(1,'callCreated',frameId,{variables:{size:segment.length},visualization:{activeRange:[start,end]},message:`Create ${frameId} for [${segment.join(', ')}].`});stack.push(frameId);frame.status='active';emit(1,'callActivated',frameId,{variables:{size:segment.length},visualization:{activeRange:[start,end]},checkpointId:`merge-next-${frameId}`,message:`Activate ${frameId}.`});const base=segment.length<=1;emit(2,'baseCaseChecked',frameId,{variables:{size:segment.length,isBaseCase:base},visualization:{activeRange:[start,end]},message:base?'The segment is a base case.':'The segment must be divided.'});if(base){const result=[...segment];emit(2,'baseCaseReached',frameId,{variables:{returnValue:result},checkpointId:`merge-base-${frameId}`,message:`Return [${result.join(', ')}].`});stack.pop();frame.status='returned';frame.returnValue=result;emit(2,'callReturned',frameId,{variables:{returnValue:result},visualization:{completedRange:[start,end]},message:`${frameId} returned.`});if(parentFrameId)frames.get(parentFrameId).status='active';return result;}
      const mid=Math.floor(segment.length/2),leftInput=segment.slice(0,mid),rightInput=segment.slice(mid);frame.localVariables.mid=start+mid;emit(3,'problemDivided',frameId,{variables:{left:leftInput,right:rightInput,leftSize:leftInput.length,rightSize:rightInput.length,mid:start+mid},visualization:{activeRange:[start,end],leftRange:[start,start+mid],rightRange:[start+mid,end]},checkpointId:`merge-divide-${frameId}`,message:`Divide into [${leftInput.join(', ')}] and [${rightInput.join(', ')}].`});emit(4,'childCallStarted',frameId,{childFrameId:`merge-${path}-L`,variables:{side:'left'},message:'Start the left recursive call.'});const left=sort(leftInput,start,frameId,`${path}-L`,depth+1);emit(4,'childCallReturned',frameId,{childFrameId:`merge-${path}-L`,variables:{leftResult:left,parentReady:false},checkpointId:`merge-left-returned-${frameId}`,message:'The left child returned; the parent still needs the right result.'});frame.status='waiting';emit(5,'childCallStarted',frameId,{childFrameId:`merge-${path}-R`,variables:{side:'right'},message:'Start the right recursive call.'});const right=sort(rightInput,start+mid,frameId,`${path}-R`,depth+1);frame.status='active';frame.localVariables={mid:start+mid,leftResult:left,rightResult:right};emit(5,'childCallReturned',frameId,{childFrameId:`merge-${path}-R`,variables:{leftResult:left,rightResult:right,parentReady:true},checkpointId:`merge-parent-ready-${frameId}`,message:'Both children returned; merging may begin.'});frame.status='combining';metrics.mergeOperations++;let i=0,j=0,output=[];emit(6,'combineStarted',frameId,{variables:{i,j,k:0},merge:{left,right,i,j,output},message:'Begin the linear merge.'});
      while(i<left.length||j<right.length){const exhausted=i>=left.length||j>=right.length;if(exhausted){const side=i>=left.length?'left':'right',chosen=i>=left.length?right[j]:left[i],advance=i>=left.length?'j':'i';output.push(chosen);if(advance==='i')i++;else j++;metrics.copies++;emit(9,'combineStep',frameId,{variables:{chosen,advance,exhausted:side,i,j,k:output.length-1},merge:{left,right,i,j,output},checkpointId:`merge-exhausted-${frameId}-${output.length}`,increment:{assignments:1,arrayAccesses:1,loopIterations:1},message:`${side} input is exhausted; copy ${chosen} from the remaining suffix.`});continue;}const leftValue=left[i],rightValue=right[j],chooseLeft=leftValue<=rightValue,chosen=chooseLeft?leftValue:rightValue,advance=chooseLeft?'i':'j',beforeI=i,beforeJ=j;output.push(chosen);if(chooseLeft)i++;else j++;metrics.copies++;emit(8,'combineStep',frameId,{variables:{leftValue,rightValue,chosen,advance,tie:leftValue===rightValue,i:beforeI,j:beforeJ,k:output.length-1},merge:{left,right,i:beforeI,j:beforeJ,output},checkpointId:`merge-choice-${frameId}-${output.length}`,increment:{comparisons:1,assignments:1,arrayAccesses:3,loopIterations:1},message:`Compare ${leftValue} and ${rightValue}; copy ${chosen} and advance ${advance}.`});}
      for(let offset=0;offset<output.length;offset++)display[start+offset]=output[offset];emit(6,'combineCompleted',frameId,{variables:{returnValue:output},merge:{left,right,i,j,output},visualization:{completedRange:[start,end]},message:`Merged result: [${output.join(', ')}].`});stack.pop();frame.status='returned';frame.returnValue=[...output];emit(6,'callReturned',frameId,{variables:{returnValue:output},visualization:{completedRange:[start,end]},message:`${frameId} returns [${output.join(', ')}].`});if(parentFrameId)frames.get(parentFrameId).status='active';return output;}
    return sort(original,0);
  }
};
function validate(array){if(!Array.isArray(array)||!array.every(Number.isFinite))throw new RangeError('Merge Sort requires a numeric array.');return [...array];}function copyFrame(frame){return structuredClone(frame);}
