export const primAlgorithm={
  id:'prim',name:{es:'Árbol de expansión mínima de Prim',en:"Prim's Minimum Spanning Tree"},category:'greedy',inputType:'undirected-weighted-graph',parameters:['vertices','edges','root'],supportedOperations:['comparisons','assignments','arrayAccesses','loopIterations'],
  pseudocode:[{id:1,text:'key[root] ← 0; key[v] ← ∞'},{id:2,text:'Q ← all vertices; T ← ∅'},{id:3,text:'while Q is not empty'},{id:4,text:'    u ← extractMin(Q)'},{id:5,text:'    add pred[u]—u to T when pred[u] ≠ null'},{id:6,text:'    for each edge (u,v) with v in Q'},{id:7,text:'        if w(u,v) < key[v]'},{id:8,text:'            key[v] ← w(u,v); pred[v] ← u'}],
  generateInput(input={}){return normalize(input);},
  execute(input,_options,recorder){const graph=normalize(input),keys=Object.fromEntries(graph.vertices.map(v=>[v.id,v.id===graph.root?0:Infinity])),predecessors=Object.fromEntries(graph.vertices.map(v=>[v.id,null])),inside=[],treeEdges=[];let queue=graph.vertices.map(v=>v.id),totalWeight=0;
    emit(recorder,1,'assignment',{root:graph.root},{keys,predecessors,inside,queue:viewQueue(queue,keys),treeEdges,totalWeight},{},{assignments:graph.vertices.length+1},'Initialize keys and predecessor vertices.');
    while(queue.length){const minimum=Math.min(...queue.map(id=>keys[id])),ties=queue.filter(id=>keys[id]===minimum).sort(),u=ties[0];if(minimum===Infinity)throw new RangeError('Prim requires a connected graph.');emit(recorder,4,'checkpoint',{minimum,tiedVertices:ties},{keys,predecessors,inside,queue:viewQueue(queue,keys),treeEdges,totalWeight},{activeVertex:u},{comparisons:Math.max(0,queue.length-1)},`Minimum key is ${minimum}.`,`prim-extract-${inside.length}`);queue=queue.filter(id=>id!==u);inside.push(u);let selectedEdge=null;if(predecessors[u]!==null){selectedEdge=findEdge(graph.edges,u,predecessors[u]);treeEdges.push(selectedEdge);totalWeight+=selectedEdge.weight;}emit(recorder,5,'extractMin',{u,key:keys[u],predecessor:predecessors[u],selectedEdge:selectedEdge?.id??null},{keys,predecessors,inside,queue:viewQueue(queue,keys),treeEdges,totalWeight},{activeVertex:u,activeEdge:selectedEdge?.id??null},{assignments:selectedEdge?3:2,arrayAccesses:1},selectedEdge?`Add ${selectedEdge.id} to the tree.`:`Add root ${u}; no predecessor edge is added.`);
      const changes=[];for(const edge of adjacent(graph.edges,u).filter(item=>queue.includes(item.v))){const changesKey=edge.weight<keys[edge.v];emit(recorder,7,'considerCandidate',{u,v:edge.v,weight:edge.weight,oldKey:keys[edge.v],changes:changesKey},{keys,predecessors,inside,queue:viewQueue(queue,keys),treeEdges,totalWeight},{activeVertex:u,activeEdge:edge.id,comparedVertex:edge.v},{comparisons:1,arrayAccesses:1,loopIterations:1},changesKey?`${edge.weight} improves key[${edge.v}].`:`Keep key[${edge.v}].`,`prim-key-${u}-${edge.v}`);if(changesKey){keys[edge.v]=edge.weight;predecessors[edge.v]=u;changes.push(edge.v);emit(recorder,8,'decreaseKey',{u,v:edge.v,newKey:edge.weight,newPredecessor:u},{keys,predecessors,inside,queue:viewQueue(queue,keys),treeEdges,totalWeight},{activeVertex:u,activeEdge:edge.id},{assignments:2,arrayAccesses:2},`Update key and predecessor for ${edge.v}.`);}}
      emit(recorder,6,'checkpoint',{u,changedVertices:changes,outside:queue},{keys,predecessors,inside,queue:viewQueue(queue,keys),treeEdges,totalWeight},{activeVertex:u},{},`Key updates from ${u} are complete.`,`prim-changes-${u}`);
    }return {edges:treeEdges.map(e=>e.id),totalWeight,predecessors,keys};
  }
};
function normalize(input){const vertices=(input.vertices??[]).map(v=>typeof v==='string'?{id:v}:{...v,id:String(v.id)}),ids=new Set(vertices.map(v=>v.id)),root=String(input.root??vertices[0]?.id??'');if(!vertices.length||ids.size!==vertices.length||!ids.has(root)||input.directed===true)throw new RangeError('Prim requires unique vertices, a valid root, and an undirected graph.');const edges=(input.edges??[]).map((e,i)=>({id:String(e.id??`e${i+1}`),from:String(e.from),to:String(e.to),weight:Number(e.weight)}));if(edges.some(e=>!ids.has(e.from)||!ids.has(e.to)||!Number.isFinite(e.weight)))throw new RangeError('Invalid edge.');return {vertices,edges,root};}
function adjacent(edges,u){return edges.flatMap(e=>e.from===u?[{...e,v:e.to}]:e.to===u?[{...e,v:e.from}]:[]);}function findEdge(edges,a,b){return edges.find(e=>(e.from===a&&e.to===b)||(e.from===b&&e.to===a));}function viewQueue(queue,keys){return queue.map(vertex=>({vertex,key:keys[vertex]})).sort((a,b)=>a.key-b.key||a.vertex.localeCompare(b.vertex));}
function emit(recorder,line,type,variables,s,visualization,increment,message,checkpointId=null){recorder.record({line,type,variables,structures:{keys:{...s.keys},predecessors:{...s.predecessors},inside:[...s.inside],queue:s.queue.map(x=>({...x})),treeEdges:s.treeEdges.map(x=>({...x})),totalWeight:s.totalWeight},visualization,increment,message:{en:message,es:message},checkpointId});}
